library(ggplot2)
library(ggthemes)
library(gghighlight)
library(ggsci)
library(Rmisc)
dat <- read.csv("mie_fig8_viability.csv")
dat2 <- summarySE(data=dat, measurevar="RFU",groupvars=c("time_h","compound"))
v <- ggplot(data = dat2) + geom_line(aes(x=time_h,y=RFU,group=compound,color=compound))+geom_ribbon(aes(x=time_h,ymin=RFU-sd,ymax=RFU+sd,fill=compound),alpha=0.5)+theme_classic()+facet_wrap(~compound)+gghighlight(use_direct_label = FALSE)
w <- v+scale_color_d3()+scale_fill_d3()+ theme(axis.line = element_line(size = 0.25, colour = "black"))+theme(text=element_text(size=12),legend.position="None")
ggsave(plot = w, width = 5, height = 5, dpi = 300, filename = "miefig8.pdf")
